name: Feature request
description: Suggest an enhancement
title: "feat: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What pain point are you facing?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred behavior/API.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Optional alternatives or workarounds.
    validations:
      required: false
